name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository - tomar codigo del repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:" # hara un nuevo tag major si en el commit colocamos un major:
        minor_pattern: "feat:" # hara un nuevo tag minor si en el commit colocamos un major:
        version_format: "${major}.${minor}.${patch}-prerelease${increment}" # cada commit que hagamos incrementara el increment
      id: version-automatic # este es un id con el que nosotros hacemos referencia a este paso
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Login el docker hub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version-automatic.outputs.version }} # Adicionalmente añadimos el latest
      run: |
        docker build -t edwardrg/teslo-shop-gh-actions:$NEW_VERSION .
        docker build -t edwardrg/teslo-shop-gh-actions:latest .
    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version-automatic.outputs.version }}
      run: |
        docker push edwardrg/teslo-shop-gh-actions:$NEW_VERSION
        docker push edwardrg/teslo-shop-gh-actions:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
